<script type="text/javascript" src="{{asset('/assets/comment/js/jquery-1.9.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/layui/build/layui.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/bootstrap/js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/config.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/function.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/comment.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/chat.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/cookie.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/ajax.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/check.js')}}"></script>
<script type="text/javascript" src="{{asset('/assets/comment/js/socket.js')}}"></script>